- test/ered_SUITE.erl
* Stabilize test suite setup    
Wait until all cluster nodes have the same view of the slots mapping.
* Pin Redis version in tests to 6.2.7
* Update testcase `t_new_cluster_master` for Redis 6.2
Manually forget the added node in the end of the testcase.
From Redis version 6.2 a node without slots becomes a replica to a selected master,
but in pre-6.2 the node was removed from the slot map triggering ered to disconnect its client to that node.
> Stabilize CI

- README.md
- src/ered_parser.erl
- test/ered_parser_tests.erl
Sets version 2 is used on OTP 24+ (which means it's implemented as a map). On OTP < 24, the old sets:set() represenation is used.
Additionally changes: Handle NaN values returned by Redis, returned as the atom 'nan'.
Document the Erlang representation of Redis datatypes in the README.
> Use sets:set() for RESP3 sets

- .github/workflows/ci.yml
- rebar.config
Drop edown and edoc since there are no edoc comments in the code anyway.
Remove rebar3_fmt from global plugins and use it only in the 'check' rebar3 profile. This means we have no online deps by default, but it can be enabled again by explicitly running 'rebar3 as check fmt'. This is used by CI.
> No online deps

- src/ered_cluster.erl
- src/ered_lib.erl
- test/ered_SUITE.erl
Adds a set of 'reconnecting' nodes, which are not yet considered 'down', just temporarily lost connection.
Don't send CLUSTER SLOTS to any node which is reconnecting or has a full command queue.
Also send CLUSTER SLOTS to a random node, since we may send multiple async CLUSTER SLOTS before we get a reply for the first one, so we don't want the same node over and over.
> Avoid sending CLUSTER SLOTS to unavailable nodes

- src/ered_client.erl
- src/ered_lib.erl
and some other minor changes, e.g. use lists:usort when sorting lists of nodes that shouldn't have duplicates.
> Don't get killed by linked process

- README.md
- src/ered_client.erl
- src/ered_cluster.erl
- test/ered_SUITE.erl
New functions 'deactivate' and 'reactivate' are added to ered_client.
When a node is removed from the cluster, the client to that node is first deactivated, then stopped after some time. When the client is deactivated, it replies to commands immediately with `{error, node_deactivated}`.
If the node comes back to the cluster and the client to this node is not yet stopped, the client is reactivated and ered recovers faster than if it would have to start a new client to that node.
> Make clients removed from slot map reject commands immediately

- src/ered_parser.erl
- test/ered_parser_tests.erl
Erlang is odd here, since Erlang requires a decimal fraction part (i.e. a dot followed by digits). The number "1e100" needs to be rewritten to "1.0e100" before parsing it using binary_to_float/1.
> Parse floats with exponent part

- README.md
- src/ered_cluster.erl
- src/ered_info_msg.erl
- test/ered_SUITE.erl
An empty response from CLUSTER SLOTS can mean that an admin has done CLUSTER RESET on a node, for example after a failover. If an empty slotmap i accepted, ered forgets all nodes and cannot recover again. Ignoring these responses instead results in repeated tries to update the slotmap until a non-empty slotmap is returned from one of the nodes.
Additional change: Include node address in info msg about updated slotmap.
> Ignore empty slotmap

- src/ered_command.erl
This avoids a few nested lists, thus a few allocations.
> Micro-optimize command-to-RESP

- src/ered.erl
- src/ered_client.erl
- src/ered_client_sup.erl
- src/ered_cluster.erl
- test/ered_SUITE.erl
This change adds a supervisor for client processes, so a client process can crash without affecting the other client processes or the ered instance. (An ered client may crash e.g. due to a bug in OTP's TLS implementation.)
To keep track of missing or dead client processes, the ered process manages monitors to all ered_client processes, so it can properly return errors to commands handled by a crashed client process. `ered:command/3,4` returns a value in all situations. `ered:command_async/4` does not always return a value though. Specifically, if the client process crashes while handling the command, the reply callback function will never be called.
Fixes #1.
> Fault tolerance

- .github/workflows/ci.yml
- src/ered.erl
- test/ered_SUITE.erl
- test/ered_client_tests.erl
- test/ered_connection_tests.erl
This PR handles the `dialyzer` warnings received from `rebar3`'s test profile.
Most warnings are corrected:
- Update the spec for ered:reply()
- Fix send command dialyzer warnings in tests
and a few expected warnings are suppressed, test only.
The CI will now also include a `dialyzer` run (on the test profile).
> Handle dialyzer warnings

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/redis-compatibility.yml
Pin the Github Action dependencies to the hash according to secure software development best practices
recommended by the Open Source Security Foundation (OpenSSF).
When developing a CI workflow, it's common to version-pin dependencies (i.e. actions/checkout@v4). However, version tags are mutable, so a malicious attacker could overwrite a version tag to point to a malicious or vulnerable commit instead.
Pinning workflow dependencies by hash ensures the dependency is immutable and its behavior is guaranteed.
This PR also adds a [dependabot](https://docs.github.com/en/code-security/dependabot) which will perform weekly checks of the Github actions used in CI.
When a newer version is found a pull request is opened to suggest a lift.
See #42
or …
> Pin versions of Github actions in CI and add dependabot for automated updates

- .github/workflows/ci.yml
- .github/workflows/redis-compatibility.yml
This sets the default permission for CI workflows to only be able to read from the repository (scope: `contents`).
A compromised action will not be able to modify the repo or
even steal secrets since all other permission-scopes are implicit set to "none", i.e. not permitted.
More about permissions and scope can be found here:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
Part of #42 and
https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> Set read-only permission for Github Actions in CI

- .github/workflows/ci.yml
- .github/workflows/db-compatibility.yml
- rebar.config
- test/ered_client_tests.erl
This PR also adds OTP-26 and 27 to the build matrix which triggered some faults, now fixed:
- Disable warning about unknown functions or types in Dialyzer  
[Starting with OTP-26](https://erlangforums.com/t/erlang-otp-26-0-released/2607/7) the unknown function or type warning is on by default.
This will make Dialyzer complain about any types for which it has no definitions or can't infer.
Gives warnings for `Unknown type supervisor:sup_ref/0` which does not seem to be an exported type.
(but also `Unknown function ct:pal/1`, `Unknown function eunit:test/1`)
- Update test empty_string_host_t() for OTP 26  
[ OTP-18543](https://www.erlang.org/patches/otp-26.0) which is introduced in OTP-26 states:
"Looking up, connecting to and sending to a host with an empty name is now handled by trying to …
> Setup Erlang/OTP in CI using a GitHub Action

- src/ered_cluster.erl
When attempting select a node to send a CLUSTER SLOTS to and all nodes are unavailable, connect to the init nodes. This is to be able to rediscover the cluster if all the IPs change at the same time and the init node is a hostname that is updated to point to the new IP addresses.
When one of them comes up, a `connection_status` message is sent to the cluster process, which is handled by calling `update_cluster_state` which in turn sends CLUSTER SLOTS to this node.
It's a bit hard to test this without a DNS server or a simulated node.
Fixes #56
> Use init nodes as fallback if all nodes are unavailable

- README.md
- src/ered_cluster.erl
- src/ered_lib.erl
- test/ered_SUITE.erl
The check is performed by sending CLUSTER SLOTS to all primaries.
Two options are added:
* `{convergence_check_timeout, timeout()}`: Time to wait for replies from the nodes. The check is performed before changing status 'cluster_not_ok' to 'cluster_ok'. Default 1000. If zero, disables the check.
* `{convergence_check_delay, timeout()}`: Time to wait before staring the check after a slot map update when the cluster status is already 'cluster_ok'. Default 5000. Set to zero to disable this extra check. Doesn't affect the above config.
Fixes #57
> Add convergence check, that all primaries return identical slot maps

- .github/workflows/ci.yml
- .github/workflows/db-compatibility.yml
- Test using latest Valkey 8 in CI.
- Test with latest OTP releases in CI.
- Store installed apt packages in cache.
> CI updates

- src/ered.erl
- src/ered_client.erl
- src/ered_cluster.erl
The callback `format_status(Opt, StatusData)` is deprecated from OTP 27 and give build warnings.
Removing them since they are optional and no-op's in our case.
https://www.erlang.org/doc/apps/stdlib/gen_server.html#c:format_status/2
> Remove use of deprecated gen_server callback `format_status/2`

- .github/typos.toml
- .github/workflows/ci.yml
- README.md
- src/ered_command.erl
- src/ered_parser.erl
- test/ered_SUITE.erl
- test/ered_connection_tests.erl
Use spell checker `typos` and run CI-jobs when pushing changes.
Includes spelling corrections.
> Add spell checker to CI

- src/ered_client.erl
- src/ered_cluster.erl
- src/ered_info_msg.erl
- test/ered_SUITE.erl
When a cluster is starting, each node might have a different view of the slotmap.
Ered can first receive a slotmap which contains a specific node, and when
querying another node that specific node might not yet be known.
When a previously known node is missing from a received slotmap the client for
that node is deactivated, but not closed until the close_wait timeout.
If the specific node resurface in the next slotmap update then the peer is
reactivated.
1. Fix a problem in `handle_info({slot_info..)` that the `closing` set still contained reactivated peers.
`NewClosing` did not contain the result of `start_clients/2`.
2. `node_is_available/2` could include nodes that are deactivated/closing.
3. Replace `{connection_down, node_deactivated}` with `node_deactivated` which don't change the …
> Fix issue with reactivation of connected clients

- README.md
- src/ered_connection.erl
- test/ered_SUITE.erl
Change the TLS connect procedure to use `ssl:connect/4` directly instead
of first connecting a TCP socket and then upgrading it to TLS.
Since we previously opened a TLS connection by first connecting a TCP socket
users needed to configure both `tcp_connect_timeout` and `tls_connect_timeout`
to get a timeout when using TLS, which was a bit confusing.
Therefor this commit adds the general connection option:
- `{connect_timeout, timeout()}`
which replaces and deprecates the following options:
- `{tcp_connect_timeout, timeout()}`
- `{tls_connect_timeout, timeout()}`
> Use `ssl:connect/4` to open TLS connections

- .github/workflows/ci.yml
- .github/workflows/db-compatibility.yml
- test/ered_SUITE.erl
- test/ered_test_utils.erl
- test/ered_test_utils.hrl
- test/ered_tls_SUITE.erl
Start a cluster with TLS and verify that ered can communicate with the cluster,
and verify the behavior when using an expired client certificate.
Some tests require the tool [faketime](https://manpages.ubuntu.com/manpages/trusty/man1/faketime.1.html) to modify the system time,
but tests are skipped if the tool is not available in PATH.
> Add basic TLS common tests

- .github/workflows/release.yml
- src/ered.app.src
* Add a CI workflow that is only run when a tag is pushed to
Github, and a check that the ered application vsn is matching
the pushed tag.    
`application:get_key(ered, vsn)` is used to get the vsn version
and the shell will return an error code when the version and
the tag is not matching, which fails the CI job.
* The `0.7.0` release provided the faulty application vsn string `0.6.0`.
Update vsn to `0.7.1` to prepare for a new release.
> Add a release CI workflow with a version check and prepare for release `0.7.1`

- src/ered_client.erl
- src/ered_connection.erl
The following issues are corrected with this PR:
- Correcting signature on function handling a `command_reply`.
The function in `ered_client` handling stray messages from a defunct client
has a faulty signature which could result it a crash.
- Correcting `batch_size` bug in connection options.   
Since the batch size counter was not increased previously
the batch size was always infinite.
> Correcting issues in `ered_client` and `ered_connection`

- src/ered_connection.erl
- test/ered_SUITE.erl
- test/ered_test_utils.erl
- test/ered_tls_SUITE.erl
When the server containers are started in common tests we wait a while before checking for node availability using an `ered_client`. If the Github CI is choked some containers might take longer time to start than our defined sleep.
Lets replace this fixed time with a common function that wait for a `connection_up` event from each node instead.
This should give faster initiations during normal times when Github CI is not choked.
Using a `connect_timeout` will also avoid failures when connecting to containers during startup.
Additionally in this PR; replace the `ered_SUITE` local function `recv/2` with the common `?MSG` macro.
> Fix intermittent failures after `docker run` in common tests

- README.md
- src/ered.app.src
- src/ered.erl
- src/ered_app.erl
- src/ered_client.erl
- src/ered_client_sup.erl
- src/ered_cluster.erl
- src/ered_cluster_sup.erl
- src/ered_dyn_cluster_sup.erl
- src/ered_info_msg.erl
- src/ered_sup.erl
- test/ered_SUITE.erl
- test/ered_client_tests.erl
- test/ered_test_utils.erl
- test/ered_tls_SUITE.erl
* Merge `ered` and `ered_cluster` processes.
The command handling code is moved from `ered` to `ered_cluster`. The
`ered` module becomes just an API module without a process of its own.
This eliminates some duplicated structures and copying between processes.
Change `ered_client_sup` into to `simple_one_for_one` supervisor.
* App and supervision tree.
Ered becomes an application with its own supervision tree.
In the API, `connect_cluster/2` replaces `start_link/2` and `close/1`
replaces `stop/1`. The processes are added to ered's own supervision tree.
An ered instance monitors the caller and closes down if the owner dies,
much like the controlling process concept in OTP's `gen_tcp` and `ssl`.
* Add info message `cluster_stopped` sent in `ered_cluster:terminate/1`.
The process traps exits …
> Make ered an application with its own supervision tree

- test/ered_SUITE.erl
- test/ered_test_utils.erl
- Wait (maximum) 60 sec for containers to be running since Github runners uses `sysctl net.ipv4.tcp_fin_timeout` set to 60 sec.
Sometimes a node container would not start, and investigations showed that we got this kind of log from a valkey/redis: `Warning: Could not create server TCP listening socket *:41006: bind: Address already in use`
- Add checks for a consistent cluster to fix intermittent issues with: `t_empty_initial_slotmap`
> Fix unstable tests in Github CI

- README.md
- src/ered_client.erl
Set client option `{select_db, non_neg_integer()}` to select a logical database after a successful connect.
> Add option to select a logical database
